### ISSUE TITLE
Cowomunication channel

### ISSUE THREAD

**Issue by Cynede** [owo-lang/rfcs#6]
IRC channel, discord server, anything else for real-time chat?

Thank yoUwU!

**Comment by ice1000** [comment]
Gitter?

**Comment by ice1000** [comment]
Test

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/49020940-93e14000-f15f-11e8-90e1-b42c4fece3be.png)
It works!

**Comment by ice1000** [comment]
Done. See update in README
